# Generated by Django 6.1 on 2026-08-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_comment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام اثر')),
                ('creator', models.CharField(max_length=200, verbose_name='نام پدیدآورنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('added', 'اضافه شد'), ('rejected', 'رد شد')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='rooms.category', verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
